# Generated by Django 5.2 on 2025-05-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='F1UserGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'f1_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='F1UserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'f1_user_permissions',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='f1user',
            options={'managed': False},
        ),
    ]
